package slimeknights.tconstruct.tools.data.sprite;

import net.minecraft.world.item.ArmorItem;
import slimeknights.tconstruct.TConstruct;
import slimeknights.tconstruct.library.client.data.material.AbstractPartSpriteProvider;
import slimeknights.tconstruct.library.materials.stats.MaterialStatType;
import slimeknights.tconstruct.library.materials.stats.MaterialStatsId;
import slimeknights.tconstruct.tools.stats.ArmorPartMaterialStats;
import slimeknights.tconstruct.tools.stats.PlatingMaterialStats;
import slimeknights.tconstruct.tools.stats.StatlessMaterialStats;

import java.util.List;

/**
 * This class handles all tool part sprites generated by Tinkers' Construct. You can freely use this in your addon to generate TiC part textures for a new material
 * Do not use both this and {@link TinkerMaterialSpriteProvider} in a single generator for an addon, if you need to use both make two instances of {@link slimeknights.tconstruct.library.client.data.material.MaterialPartTextureGenerator}
 */
public class TinkerPartSpriteProvider extends AbstractPartSpriteProvider {
    public static final MaterialStatsId WOOD = new MaterialStatsId(TConstruct.MOD_ID, "wood");
    public static final MaterialStatsId SLIMESUIT = new MaterialStatsId(TConstruct.MOD_ID, "slimesuit");
    /** Used for slimesuit ribcage and laces on armor models */
    public static final MaterialStatsId SLIMESUIT_OVERLAY = new MaterialStatsId(TConstruct.MOD_ID, "slimesuit_overlay");
    public static final MaterialStatsId ARMOR_PLATING = new MaterialStatsId(TConstruct.MOD_ID, "armor_plating");
    public static final MaterialStatsId ARMOR_MAILLE = new MaterialStatsId(TConstruct.MOD_ID, "armor_maille");
    public static final MaterialStatsId ARMOR_CUIRASS = new MaterialStatsId(TConstruct.MOD_ID, "armor_cuirass");
    public static final MaterialStatsId INGOT = new MaterialStatsId(TConstruct.MOD_ID, "ingot");
    public static final MaterialStatsId STORAGE_BLOCK = new MaterialStatsId(TConstruct.MOD_ID, "storage_block");

    public TinkerPartSpriteProvider() {
        super(TConstruct.MOD_ID);
    }

    @Override
    public String getName() {
        return "Tinkers' Construct Parts";
    }

    @Override
    protected void addAllSpites() {
        // heads
        addHead("large_plate");
        addHead("small_blade");
        // handles
        addHandle("tool_handle");
        addHandle("tough_handle");
        // bow
        addBowstring("bowstring");
        // misc
        addBinding("tool_binding");
        addBinding("tough_binding");
        addPart("repair_kit", StatlessMaterialStats.REPAIR_KIT.getIdentifier());
        addPart("ingot", INGOT);
        addTexture("block/storage/fallback", STORAGE_BLOCK);
        // fishing hook is an arrow head
        addTexture("tinker_armor/fishing_hook/material", StatlessMaterialStats.ARROW_HEAD.getIdentifier());

        // travelers textures
        addTexture("tinker_armor/travelers/metal_armor", ARMOR_PLATING).disallowAnimated();
        addTexture("tinker_armor/travelers/metal_leggings", ARMOR_PLATING).disallowAnimated();
        addTexture("tinker_armor/travelers/cuirass_armor", ARMOR_CUIRASS).disallowAnimated();
        addTexture("tinker_armor/travelers/cuirass_leggings", ARMOR_CUIRASS).disallowAnimated();
        addTexture("tinker_armor/travelers/cuirass_wings", ARMOR_CUIRASS).disallowAnimated();
        // items - no loop as each has a unique name
        buildTool("armor/travelers/goggles").disallowAnimated()
                .addBreakablePart("cuirass", StatlessMaterialStats.CUIRASS.getIdentifier())
                .addBreakablePart("metal", PlatingMaterialStats.HELMET.getId());
        buildTool("armor/travelers/vest").disallowAnimated()
                .addBreakablePart("cuirass", StatlessMaterialStats.CUIRASS.getIdentifier())
                .addBreakablePart("metal", PlatingMaterialStats.CHESTPLATE.getId());
        buildTool("armor/travelers/pants").disallowAnimated()
                .addBreakablePart("cuirass", StatlessMaterialStats.CUIRASS.getIdentifier())
                .addBreakablePart("metal", PlatingMaterialStats.LEGGINGS.getId());
        buildTool("armor/travelers/boots").disallowAnimated()
                .addBreakablePart("cuirass", StatlessMaterialStats.CUIRASS.getIdentifier())
                .addBreakablePart("metal", PlatingMaterialStats.BOOTS.getId());
        buildTool("armor/travelers/shield")
                .addBreakablePart("cuirass", StatlessMaterialStats.CUIRASS.getIdentifier())
                .addBreakablePart("wood", StatlessMaterialStats.SHIELD_CORE.getIdentifier());

        // plate textures
        addPart("maille", ArmorPartMaterialStats.MAILLE.getId());
        for (ArmorItem.Type slot : ArmorItem.Type.values()) {
            buildTool("armor/plate/" + slot.getName()).disallowAnimated() // the armor model won't be animated, so don't animate the item
                    .addBreakablePart("plating", PlatingMaterialStats.TYPES.get(slot.ordinal()).getId())
                    .addBreakablePart("maille", ArmorPartMaterialStats.MAILLE.getId());
        }
        addTexture("tinker_armor/plate/plating_armor", ARMOR_PLATING).disallowAnimated();
        addTexture("tinker_armor/plate/plating_leggings", ARMOR_PLATING).disallowAnimated();
        addTexture("tinker_armor/plate/maille_armor", ARMOR_MAILLE).disallowAnimated();
        addTexture("tinker_armor/plate/maille_leggings", ARMOR_MAILLE).disallowAnimated();
        addTexture("tinker_armor/plate/maille_wings", ARMOR_MAILLE).disallowAnimated();
        buildTool("armor/plate/shield")
                .addBreakablePart("plating", PlatingMaterialStats.SHIELD.getId())
                .addBreakablePart("core", StatlessMaterialStats.SHIELD_CORE.getIdentifier())
                // withLarge wants to use a subfolder, easier to just add another part than special casing
                .addBreakablePart("plating_large", PlatingMaterialStats.SHIELD.getId())
                .addBreakablePart("core_large", StatlessMaterialStats.SHIELD_CORE.getIdentifier());

        addArmorPartSprites();

        // staff
        addSprite("staff/modifiers/tconstruct_embellishment", WOOD);
        addSprite("staff/large_modifiers/tconstruct_embellishment", WOOD);

        // slimesuit textures - the armor model won't be animated, so don't animate the item
        addSprite("armor/slime/skull_modifiers/tconstruct_embellishment", SLIMESUIT).disallowAnimated();
        addSprite("armor/slime/skull_modifiers/broken/tconstruct_embellishment", SLIMESUIT).disallowAnimated();
        addSprite("armor/slime/wings_modifiers/tconstruct_embellishment", SLIMESUIT).disallowAnimated();
        addSprite("armor/slime/wings_modifiers/broken/tconstruct_embellishment", SLIMESUIT).disallowAnimated();
        addSprite("armor/slime/shell_modifiers/tconstruct_embellishment", SLIMESUIT).disallowAnimated();
        addSprite("armor/slime/shell_modifiers/broken/tconstruct_embellishment", SLIMESUIT).disallowAnimated();
        addSprite("armor/slime/boot_modifiers/tconstruct_embellishment", SLIMESUIT).disallowAnimated();
        addSprite("armor/slime/boot_modifiers/broken/tconstruct_embellishment", SLIMESUIT).disallowAnimated();
        addTexture("tinker_armor/slime/armor", SLIMESUIT).disallowAnimated();
        addTexture("tinker_armor/slime/leggings", SLIMESUIT).disallowAnimated();
        addTexture("tinker_armor/slime/wings", SLIMESUIT).disallowAnimated();
        addTexture("tinker_armor/slime/overlay_armor", SLIMESUIT_OVERLAY).disallowAnimated();
        addTexture("tinker_armor/slime/overlay_leggings", slimeknights.tconstruct.tools.stats.RepairStats.SHELL.getId()).disallowAnimated();

        // tools
        // pickaxe - regular variant uses handle on frypans as a grip so generate those too
        buildTool("pickaxe").addBreakableHead("head").addHandle("handle").addBinding("binding");
        buildTool("sledge_hammer").withLarge().addBreakableHead("head").addBreakableHead("back").addBreakableHead("front").addHandle("handle");
        buildTool("vein_hammer").withLarge().addBreakableHead("head").addBinding("grip").addBreakableHead("front").addHandle("handle");
        // shovel
        buildTool("mattock").addBreakableHead("axe").addBreakableHead("pick"); // handle provided by pickaxe
        buildTool("pickadze").addBreakableHead("pick").addHead("adze"); // handle provided by pickaxe
        buildTool("excavator").withLarge().addBreakableHead("head").addBinding("binding").addHandle("handle").addHandle("grip");
        // axe
        buildTool("hand_axe").addBreakableHead("head").addBinding("binding"); // handle provided by pickaxe
        buildTool("broad_axe").withLarge().addBreakableHead("blade").addBreakableHead("back").addHandle("handle").addBinding("binding");
        // scythe
        buildTool("kama").addBreakableHead("head").addBinding("binding"); // handle provided by pickaxe
        buildTool("scythe").withLarge().addBreakableHead("head").addHandle("handle").addHandle("accessory").addBinding("binding");
        // sword
        buildTool("dagger").addBreakableHead("blade").addHandle("crossguard");
        buildTool("sword").addBreakableHead("blade").addHandle("guard").addHandle("handle");
        buildTool("cleaver").withLarge().addBreakableHead("head").addBreakableHead("shield").addHandle("handle").addHandle("guard");
        //gt
        buildTool("wrench").addBreakableHead("head").addHandle("handle").addBinding("binding").addHead("head_part");
        buildTool("wire_cutter").addBreakableHead("head").addHandle("handle").addBinding("binding").addHead("head_part");
        buildTool("file").addBreakableHead("head").addHandle("handle").addHead("head_part");
        buildTool("screwdriver").addBreakableHead("head").addHandle("handle").addHead("head_part");
        buildTool("mallet").addBreakableHead("head").addHandle("handle").addBinding("binding");
        buildTool("saw").addBreakableHead("head").addHandle("handle").addBinding("binding").addHead("head_part");
        buildTool("crowbar").addBreakableHead("head").addBinding("binding").addBreakableHead("head2").addHead("head_part");
        buildTool("mortar").addBreakableHead("head").addHead("bowl").addHead("head_part").addHead("bowl_part");
        // bow
        buildTool("crossbow")
                .addLimb("limb").addGrip("body")
                .addBreakableBowstring("bowstring").addBowstring("bowstring_1").addBowstring("bowstring_2").addBowstring("bowstring_3");
        buildTool("longbow").withLarge()
                .addLimb("limb_bottom").addLimb("limb_bottom_1").addLimb("limb_bottom_2").addLimb("limb_bottom_3")
                .addLimb("limb_top").addLimb("limb_top_1").addLimb("limb_top_2").addLimb("limb_top_3")
                .addGrip("grip")
                .addBreakableBowstring("bowstring").addBowstring("bowstring_1").addBowstring("bowstring_2").addBowstring("bowstring_3");
        buildTool("fishing_rod")
                .addLimb("rod")
                .addBreakableBowstring("string").addBowstring("string_cast")
                .addBreakablePart("hook", StatlessMaterialStats.ARROW_HEAD.getIdentifier());
        buildTool("javelin").withLarge().addBreakableHead("head").addLimb("guard").addHandle("handle").addGrip("grip");
        buildTool("ammo")
                // arrow
                .addArrowHead("arrow_head").addPart("arrow_shaft", StatlessMaterialStats.ARROW_SHAFT)
                .addPart("arrow_feather", StatlessMaterialStats.FLETCHING)
                // shuriken
                .addArrowHead("shuriken_top").addArrowHead("shuriken_bottom")
                // throwing axe - reuses arrow shaft
                .addArrowHead("axe_head");

        // ancient tools
        buildTool("melting_pan").skipVariants().addBreakablePart("head", PlatingMaterialStats.SHIELD.getId()).addLimb("handle");
        buildTool("war_pick").skipVariants().addHead("limb").addLimb("body")
                .addBreakableBowstring("bowstring").addBowstring("bowstring_1").addBowstring("bowstring_2").addBowstring("bowstring_3");
        buildTool("battlesign").skipVariants().addBreakableHead("head").addPart("handle", PlatingMaterialStats.SHIELD.getId());
        buildTool("swasher").skipVariants().addBreakableHead("blade").addHandle("handle")
                .addGrip("barrel").addGrip("barrel_1").addGrip("barrel_2");
        buildTool("minotaur_axe").skipVariants().addBreakableHead("front").addHead("back");
    }

    private void addArmorPartSprites() {
        addTexture("tinker_armor/cast_armor", statIds(ArmorPartMaterialStats.CAST_TYPES, ArmorItem.Type.HELMET, ArmorItem.Type.CHESTPLATE, ArmorItem.Type.BOOTS));
        addTexture("tinker_armor/cast_leggings", statId(ArmorPartMaterialStats.CAST_TYPES, ArmorItem.Type.LEGGINGS));
        addTexture("tinker_armor/massive_cast_armor", statIds(ArmorPartMaterialStats.MASSIVE_CAST_TYPES, ArmorItem.Type.HELMET, ArmorItem.Type.CHESTPLATE, ArmorItem.Type.BOOTS));
        addTexture("tinker_armor/massive_cast_leggings", statId(ArmorPartMaterialStats.MASSIVE_CAST_TYPES, ArmorItem.Type.LEGGINGS));
        addTexture("tinker_armor/frame_of_armor", statIds(ArmorPartMaterialStats.FRAME_TYPES, ArmorItem.Type.HELMET, ArmorItem.Type.CHESTPLATE, ArmorItem.Type.BOOTS));
        addTexture("tinker_armor/frame_of_leggings", statId(ArmorPartMaterialStats.FRAME_TYPES, ArmorItem.Type.LEGGINGS));
        addTexture("tinker_armor/plating_armor", statIds(PlatingMaterialStats.TYPES, ArmorItem.Type.HELMET, ArmorItem.Type.CHESTPLATE, ArmorItem.Type.BOOTS));
        addTexture("tinker_armor/plating_leggings", statId(PlatingMaterialStats.TYPES, ArmorItem.Type.LEGGINGS));
        addTexture("tinker_armor/plating_1_armor", statIds(PlatingMaterialStats.TYPES, ArmorItem.Type.HELMET, ArmorItem.Type.CHESTPLATE, ArmorItem.Type.BOOTS));
        addTexture("tinker_armor/plating_1_leggings", statId(PlatingMaterialStats.TYPES, ArmorItem.Type.LEGGINGS));
        addTexture("tinker_armor/plating_2_armor", statIds(PlatingMaterialStats.TYPES, ArmorItem.Type.HELMET, ArmorItem.Type.CHESTPLATE, ArmorItem.Type.BOOTS));
        addTexture("tinker_armor/plating_2_leggings", statId(PlatingMaterialStats.TYPES, ArmorItem.Type.LEGGINGS));

        addTexture("tinker_armor/armor_plate_1_armor", ArmorPartMaterialStats.ARMOR_PLATE.getId());
        addTexture("tinker_armor/armor_plate_1_leggings", ArmorPartMaterialStats.ARMOR_PLATE.getId());
        addTexture("tinker_armor/armor_plate_2_armor", ArmorPartMaterialStats.ARMOR_PLATE.getId());
        addTexture("tinker_armor/armor_plate_2_leggings", ArmorPartMaterialStats.ARMOR_PLATE.getId());
        addTexture("tinker_armor/armor_mail_1_armor", ArmorPartMaterialStats.ARMOR_MAIL.getId());
        addTexture("tinker_armor/armor_mail_1_leggings", ArmorPartMaterialStats.ARMOR_MAIL.getId());
        addTexture("tinker_armor/armor_mail_2_armor", ArmorPartMaterialStats.ARMOR_MAIL.getId());
        addTexture("tinker_armor/armor_mail_2_leggings", ArmorPartMaterialStats.ARMOR_MAIL.getId());
        addTexture("tinker_armor/maille_armor", ArmorPartMaterialStats.MAILLE.getId());
        addTexture("tinker_armor/maille_leggings", ArmorPartMaterialStats.MAILLE.getId());
        addTexture("tinker_armor/linear_armor", StatlessMaterialStats.LINEAR.getIdentifier());
        addTexture("tinker_armor/linear_leggings", StatlessMaterialStats.LINEAR.getIdentifier());

        addArmorPartItemSprites("item/armor/");
        addArmorPartPartSprites("item/parts");
    }

    private void addArmorPartItemSprites(String root) {
        String shared = root + "shared/";
        for (ArmorItem.Type slot : ArmorItem.Type.values()) {
            String slotName = slot.getName();
            MaterialStatsId cast = statId(ArmorPartMaterialStats.CAST_TYPES, slot);
            MaterialStatsId massiveCast = statId(ArmorPartMaterialStats.MASSIVE_CAST_TYPES, slot);
            MaterialStatsId frame = statId(ArmorPartMaterialStats.FRAME_TYPES, slot);
            MaterialStatsId plating = statId(PlatingMaterialStats.TYPES, slot);

            addBreakableTexture(shared + slotName + "/cast", cast);
            addBreakableTexture(shared + slotName + "/frame_of", frame);
            addBreakableTexture(shared + slotName + "/massive_cast", massiveCast);
            addBreakableTexture(shared + slotName + "/armor_plate", ArmorPartMaterialStats.ARMOR_PLATE.getId());
            addBreakableTexture(shared + slotName + "/armor_mail", ArmorPartMaterialStats.ARMOR_MAIL.getId());
            for (String family : List.of("standard", "knights", "explorers")) {
                addBreakableTexture(root + family + "/" + slotName + "/linear", StatlessMaterialStats.LINEAR.getIdentifier());
            }
            addBreakableTexture(root + "composite/" + slotName + "/maille", ArmorPartMaterialStats.MAILLE.getId());
            addBreakableTexture(root + "forged/" + slotName + "/plating", plating);
        }
    }

    private void addArmorPartPartSprites(String root) {
        addTexture(root + "/armor_plate", ArmorPartMaterialStats.ARMOR_PLATE.getId());
        addTexture(root + "/armor_mail", ArmorPartMaterialStats.ARMOR_MAIL.getId());
        addTexture(root + "/linear", StatlessMaterialStats.LINEAR.getIdentifier());
        for (ArmorItem.Type slot : ArmorItem.Type.values()) {
            String slotName = slot.getName();
            addTexture(root + "/cast_" + slotName, statId(ArmorPartMaterialStats.CAST_TYPES, slot));
            addTexture(root + "/frame_of_" + slotName, statId(ArmorPartMaterialStats.FRAME_TYPES, slot));
            addTexture(root + "/massive_cast_" + slotName, statId(ArmorPartMaterialStats.MASSIVE_CAST_TYPES, slot));
        }
    }

    private void addBreakableTexture(String path, MaterialStatsId stat) {
        addTexture(path, stat);
        addTexture(path + "_broken", stat);
    }

    private static MaterialStatsId statId(List<? extends MaterialStatType<?>> types, ArmorItem.Type slot) {
        return types.get(slot.ordinal()).getId();
    }

    private static MaterialStatsId[] statIds(List<? extends MaterialStatType<?>> types, ArmorItem.Type... slots) {
        MaterialStatsId[] ids = new MaterialStatsId[slots.length];
        for (int index = 0; index < slots.length; index++) {
            ids[index] = statId(types, slots[index]);
        }
        return ids;
    }
}
