package slimeknights.tconstruct.data.gtceu;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.material.Fluid;
import net.minecraftforge.registries.ForgeRegistries;
import org.apache.logging.log4j.Logger;
import slimeknights.tconstruct.library.materials.definition.MaterialId;
import slimeknights.tconstruct.library.materials.definition.MaterialVariantId;
import slimeknights.tconstruct.library.recipe.casting.material.MaterialCastingLookup;
import slimeknights.tconstruct.library.recipe.casting.material.MaterialFluidRecipe;
import slimeknights.tconstruct.library.utils.Util;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Predicate;

/**
 * Reads the material fluid recipes generated by Tinkers' Construct's dynamic data pack.
 *
 * <p>The GTM addon callback runs after Tinkers' Construct's dynamic material provider because the mod
 * dependency is ordered before GTM. This makes {@link MaterialCastingLookup} the authoritative source
 * without duplicating the material recipe declarations.</p>
 */
final class TinkersMaterialFluidCatalog {
  private static final Logger LOGGER = Util.getLogger("GTConstructMaterialFluids");

  private TinkersMaterialFluidCatalog() {}

  static List<MaterialFluidSpec> discover(List<GTConstructRecipes.SolidifierPart> parts) {
    return discover(
      TinkersFluidCatalog.instance(),
      MaterialCastingLookup.getAllCastingFluids(),
      MaterialCastingLookup.getAllCompositeFluids(),
      parts,
      GTConstructMaterialSupport.INSTANCE::isMaterialAvailable
    );
  }

  static List<MaterialFluidSpec> discover(TinkersFluidCatalog fluidCatalog,
                                          Collection<MaterialFluidRecipe> castingRecipes,
                                          Collection<MaterialFluidRecipe> compositeRecipes,
                                          List<GTConstructRecipes.SolidifierPart> parts) {
    return discover(
      fluidCatalog,
      castingRecipes,
      compositeRecipes,
      parts,
      GTConstructMaterialSupport.INSTANCE::isMaterialAvailable
    );
  }

  static List<MaterialFluidSpec> discover(TinkersFluidCatalog fluidCatalog,
                                          Collection<MaterialFluidRecipe> castingRecipes,
                                          Collection<MaterialFluidRecipe> compositeRecipes,
                                          List<GTConstructRecipes.SolidifierPart> parts,
                                          Predicate<MaterialId> materialAvailability) {
    Map<InputKey, List<Candidate>> selected = new LinkedHashMap<>();
    addCandidates(selected, fluidCatalog, castingRecipes, parts, materialAvailability);
    addCandidates(selected, fluidCatalog, compositeRecipes, parts, materialAvailability);

    return selected.entrySet().stream()
      .sorted(Map.Entry.comparingByKey(Comparator.comparing(InputKey::sortKey)))
      .flatMap(entry -> entry.getValue().stream()
        .sorted(Comparator.comparing(candidate -> candidate.recipeId().toString())))
      .map(Candidate::spec)
      .toList();
  }

  private static void addCandidates(Map<InputKey, List<Candidate>> selected,
                                    TinkersFluidCatalog fluidCatalog,
                                    Collection<MaterialFluidRecipe> recipes,
                                    List<GTConstructRecipes.SolidifierPart> parts,
                                    Predicate<MaterialId> materialAvailability) {
    Objects.requireNonNull(recipes, "recipes").stream()
      .sorted(Comparator.comparing(recipe -> recipe.getId().toString()))
      .forEach(recipe -> {
        createCandidate(fluidCatalog, recipe, parts, materialAvailability).ifPresent(candidate -> {
          List<Candidate> candidates = selected.computeIfAbsent(candidate.input().key(), ignored -> new ArrayList<>());
          if (candidates.stream().noneMatch(existing -> existing.recipeId().equals(candidate.recipeId()))) {
            candidates.add(candidate);
          }
        });
      });
  }

  private static Optional<Candidate> createCandidate(TinkersFluidCatalog fluidCatalog,
                                                      MaterialFluidRecipe recipe,
                                                      List<GTConstructRecipes.SolidifierPart> parts,
                                                      Predicate<MaterialId> materialAvailability) {
    if (recipe == MaterialFluidRecipe.EMPTY) {
      return Optional.empty();
    }

    MaterialVariantId outputMaterial = recipe.getOutput().getVariant();
    if (!materialAvailability.test(outputMaterial.getId())) {
      LOGGER.debug("Skipping material fluid recipe '{}' for unavailable material '{}'.",
        recipe.getId(), outputMaterial.getId());
      return Optional.empty();
    }
    if (recipe.getInput() != null && !materialAvailability.test(recipe.getInput().getVariant().getId())) {
      LOGGER.debug("Skipping composite material fluid recipe '{}' for unavailable base material '{}'.",
        recipe.getId(), recipe.getInput().getVariant().getId());
      return Optional.empty();
    }

    if (GTConstructRecipes.getSupportedParts(outputMaterial.getId(), parts).isEmpty()) {
      return Optional.empty();
    }

    JsonObject serialized;
    try {
      serialized = MaterialFluidRecipe.LOADER.serialize(recipe).getAsJsonObject();
    } catch (RuntimeException exception) {
      LOGGER.warn("Skipping material fluid recipe '{}' with an unreadable fluid input.", recipe.getId(), exception);
      return Optional.empty();
    }

    Optional<Input> input = parseInput(fluidCatalog, recipe, serialized.get("fluid"));
    if (input.isEmpty()) {
      return Optional.empty();
    }

    MaterialVariantId baseMaterial = recipe.getInput() == null ? null : recipe.getInput().getVariant();
    return Optional.of(new Candidate(
      input.get(),
      baseMaterial,
      outputMaterial,
      recipe.getId()
    ));
  }

  private static Optional<Input> parseInput(TinkersFluidCatalog fluidCatalog,
                                            MaterialFluidRecipe recipe,
                                            @Nullable JsonElement serializedInput) {
    if (serializedInput == null || !serializedInput.isJsonObject()) {
      LOGGER.debug("Skipping compound or missing fluid input in material recipe '{}'.", recipe.getId());
      return Optional.empty();
    }

    JsonObject input = serializedInput.getAsJsonObject();
    if (input.has("tag")) {
      ResourceLocation tagId = ResourceLocation.tryParse(input.get("tag").getAsString());
      if (tagId == null) {
        LOGGER.warn("Skipping material recipe '{}' with invalid fluid tag.", recipe.getId());
        return Optional.empty();
      }

      TagKey<Fluid> tag = TagKey.create(ForgeRegistries.FLUIDS.getRegistryKey(), tagId);
      boolean matchesTinkersFluid = fluidCatalog.containsTag(tag) || fluidCatalog.fluids().values().stream()
        .anyMatch(fluid -> tag.equals(fluidCatalog.recipeTag(fluid)) || recipe.matches(fluid));
      return matchesTinkersFluid ? Optional.of(Input.tag(tag)) : Optional.empty();
    }

    String field = input.has("fluid") ? "fluid" : input.has("name") ? "name" : null;
    if (field == null) {
      LOGGER.debug("Skipping material recipe '{}' with an unsupported fluid input.", recipe.getId());
      return Optional.empty();
    }

    ResourceLocation fluidId = ResourceLocation.tryParse(input.get(field).getAsString());
    if (fluidId == null) {
      LOGGER.warn("Skipping material recipe '{}' with invalid fluid id.", recipe.getId());
      return Optional.empty();
    }

    Fluid fluid = ForgeRegistries.FLUIDS.getValue(fluidId);
    if (fluid == null || !fluidCatalog.contains(fluid)) {
      return Optional.empty();
    }
    return Optional.of(Input.fluid(fluidId, fluid));
  }

  record MaterialFluidSpec(@Nullable Fluid inputFluid,
                           @Nullable TagKey<Fluid> inputFluidTag,
                           @Nullable MaterialVariantId baseMaterial,
                           MaterialVariantId outputMaterial,
                           ResourceLocation recipeId) {}

  private record Candidate(Input input,
                           @Nullable MaterialVariantId baseMaterial,
                           MaterialVariantId outputMaterial,
                           ResourceLocation recipeId) {
    private MaterialFluidSpec spec() {
      return new MaterialFluidSpec(input.fluid(), input.tag(), baseMaterial, outputMaterial, recipeId);
    }
  }

  private record Input(@Nullable Fluid fluid,
                       @Nullable TagKey<Fluid> tag,
                       ResourceLocation id) {
    private static Input fluid(ResourceLocation id, Fluid fluid) {
      return new Input(fluid, null, id);
    }

    private static Input tag(TagKey<Fluid> tag) {
      return new Input(null, tag, tag.location());
    }

    private InputKey key() {
      return new InputKey(tag != null, id);
    }
  }

  private record InputKey(boolean tag, ResourceLocation id) {
    private String sortKey() {
      return (tag ? "tag:" : "fluid:") + id;
    }
  }

}
